#!/usr/bin/env bash

source .env 2> /dev/null

TERM=xterm-256color

COMMAND=$1

arg1=$1
arg2=$2

args=""

dc="docker-compose -p ${APP_NAME} ${args}"

php="php"
db="db_testing"
db_testing="db_testing"
cache="cache"

ADDRESS=${DOCKER_BRIDGE} || 'localhost'
MESSAGE="http://${ADDRESS}"

case ${COMMAND} in
  init)
    echo "Choose your OS:"
    select name in "win" "linux" "macos" ;
    do
      case ${name} in
        win|macos)
          cp -n ./docker/docker-compose.example.yml docker-compose.yml

        ;;

        linux)
          cp -n ./docker/docker-compose.example.yml docker-compose.yml

        ;;

      esac
    break
    done
    cp -n .env.example .env
    cp -n .env.testing.example .env.testing
    echo "Configuration done."
    echo "Change .env file and run './we build'."
  ;;
  build)
    sudo chmod 777 -R .
    sudo sysctl -w vm.max_map_count=262144
    ${dc} up --build --force-recreate -d
  ;;
  rebuild)
    ${dc} up -d --build --force-recreate --no-deps ${arg2}

  ;;
  start)
    sudo chmod 777 -R .
    sudo sysctl -w vm.max_map_count=262144
    ${dc} start
    echo ${MESSAGE}

  ;;
  stop)
    ${dc} stop

  ;;
  down)
    ${dc} down

  ;;
  logs)
    ${dc} logs -f

  ;;
  ps)
    ${dc} ps

  ;;
  restart)
    ${dc} restart
    echo ${MESSAGE}

  ;;
  php)
    ${dc} exec ${php} bash

  ;;
  db)
    ${dc} exec ${db} bash

  ;;
  db_testing)
    ${dc} exec ${db_testing} bash

  ;;
  cache)
    ${dc} exec ${cache} bash

  ;;
  info)
    echo https://${DOCKER_BRIDGE} - site

  ;;
  help|--help)
    echo "Usage:

    init      : Init docker configuration.
    build     : Building containers.
    rebuild   : Rebuilding container (add name of service after command. Example : rebuild node - for rebuild node service).
    start     : To start containers.
    stop      : To stop containers.
    down      : Destroy containers.
    restart   : Destroy containers.
    logs      : Show logs from containers.
    ps        : Show status for containers.
    db        : Go to inside db container.
    db_testing: Go to inside db_testing container.
    cache     : Go to inside cache container.
    help      : See this help.
    "

  ;;
esac
